name: 🔄 Sync Mirrors & Update Templates

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight

jobs:
  update-templates:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lib/requirements.txt
          
      - name: Download latest templates
        run: python lib/download.py
        
      - name: Combine templates
        run: python lib/combine.py
        
      # - name: Validate templates
      #   run: python lib/validate.py
        
      - name: List templates
        run: python lib/list.py
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          git add templates.json
          
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to templates.json"
          else
            git commit -m "Update templates.json [skip ci]"
            git push
          fi
